//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_image
{
    using System;
    using System.Collections.Generic;
    
    public partial class primer
    {
        public int id { get; set; }
        public string opisanie { get; set; }
        public byte[] photo_fail { get; set; }
    }
}
